audit_header: false
title: Honolulu Real Estate Video Blog with Jon Mann
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Jon Mann
  title: Principal Broker, Owner, Author
  license_number:
  about_markdown: |
    Jon S. Mann Real Estate, LLC, is a full service Hawaii real estate brokerage dedicated to exceeding client expectations by assisting, advising, and representing buyers and sellers through the residential real estate purchase and sales process.

    At Jon S. Mann Real Estate, LLC, we hope to make all the difference in our clients' search for their new home on the island of Oahu or the sale of their existing home. You can rest assured that we have the skills and the commitment that it takes to successfully complete your transaction.  Call today and schedule an appointment for consultation.
  market: Honolulu
  brand: Jon S. Mann Real Estate, LLC
  brokerage:
  address: 1888 Kalakaua Ave, Suite C-312<br>Honolulu, HI 96815
  phone: 808-728-1230
  phone_type:
  phone2:
  phone2_type:
  email: JonMann808@Gmail.com
  url: http://www.LocalRealEstateAgencyHonolulu.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.localrealestateagencyhonolulu.com/s/Find-Out-How-Much-Your-Hawaii-Home-Is-Worth
  second_CTA_text: Home Search
  second_CTA_URL: http://www.localrealestateagencyhonolulu.com/search.aspx?&position=20.57142977022099,-157.03189414999997,8

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.localrealestateagencyhonolulu.com/s/Find-Out-How-Much-Your-Hawaii-Home-Is-Worth

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.localrealestateagencyhonolulu.com/search.aspx?&position=20.57142977022099,-157.03189414999997,8

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Jon-S-Mann-Principal-Broker-for-Jon-S-Mann-Real-Estate-LLC-Rb-19922-384221478351890/
  linkedin_url: http://www.linkedin.com/in/jon-s-mann-69a70a22
  gplus_url:
  youtube_url:
  twitter_url: https://twitter.com/jonmann808
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#00457c'
  theme_color: '#5d9731'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
